apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-management
  labels:
    app: team-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-management
  template:
    metadata:
      labels:
        app: team-management
    spec:
      containers:
        - name: team-management
          image: dantunes/team-management
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 20Mi
              cpu: 100m
            limits:
              memory: 20Mi
              cpu: 100m

        
    