// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DeleteUseCase is an autogenerated mock type for the DeleteUseCase type
type DeleteUseCase struct {
	mock.Mock
}

// Handle provides a mock function with given fields: id
func (_m *DeleteUseCase) Handle(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDeleteUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteUseCase creates a new instance of DeleteUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteUseCase(t mockConstructorTestingTNewDeleteUseCase) *DeleteUseCase {
	mock := &DeleteUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
