// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	domain "team-management/members/domain"

	mock "github.com/stretchr/testify/mock"
)

// MembersRepositoryReader is an autogenerated mock type for the MembersRepositoryReader type
type MembersRepositoryReader struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *MembersRepositoryReader) Get(id string) (*domain.Member, error) {
	ret := _m.Called(id)

	var r0 *domain.Member
	if rf, ok := ret.Get(0).(func(string) *domain.Member); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Member)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMembersRepositoryReader interface {
	mock.TestingT
	Cleanup(func())
}

// NewMembersRepositoryReader creates a new instance of MembersRepositoryReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMembersRepositoryReader(t mockConstructorTestingTNewMembersRepositoryReader) *MembersRepositoryReader {
	mock := &MembersRepositoryReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
