apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    app: team-management
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo"